### ISSUE TITLE
Make RenderPipeline "atomic" & impl fast repainting alogrithm

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#54]
# Change the meaning of `RenderPipeline`

It is a collection of *atomic* paint operations (aka `RenderOps` at various `ZOrder`s); each `RenderOps` is made up of a vec of `RenderOp`. It contains `Map<ZOrder, Vec<RenderOps>>`, eg:
- `ZOrder::Normal` => vec![`ResetColor`, `MoveCursorPositionAbs(..)`, `PrintTextWithAttributes(..)`]
- `ZOrder::Glass` => vec![`ResetColor`, `MoveCursorPositionAbs(..)`, `PrintTextWithAttributes(..)`]
- etc.

# What is an atomic paint operation?
1. It moves the cursor using:
    1. `RenderOp::MoveCursorPositionAbs`
    2. `RenderOp::MoveCursorPositionRelTo`
2.  And it does not assume that the cursor is in the correct position from some other previously executed operation! 
3. So there are no side effects when re-ordering or omitting painting an atomic paint operation (eg in the case where it has already been painted before).

# Paint optimization
In order to ensure that things on the terminal screen aren't being needlessly drawn (when they
have already been drawn before and are on screen), it is important to keep track of the position
and bounds of each [RenderOps]. This allows [optimized_paint::clear_flex_box] to perform its
magic by clearing out the space for a [RenderOps] before it is painted. This is needed for
managing cursor movement (cursors are painted when moved, but the old cursor doesn't get
cleared).

# Tasks
- [x] Change `RenderPipeline` to hold a `Vec<RenderOps>` for each `ZOrder`
- [x] Update the docs for `TWData` to make it explicit when the `cursor_position` is safe to use.
- [x] Copy the content of this comment into `RenderOps`
- [x] Implement "dirty paint" algorithm
  - [x] Save the rendered pipeline in `TWData`
  - [x] re-render when the # of render ops is different in each layer
  - [x] other cases for not re-rendering

A more comprehensive fix to this will arrive when this issue is fixed https://github.com/r3bl-org/r3bl_rs_utils/issues/46

**Comment by nazmulidris** [comment]
From https://github.com/r3bl-org/r3bl_rs_utils/commit/3e1861cd7e482904a9004c89b25b50f7075af9a4

Some optimization had to be done in paint.rs to ensure that caret
movements were handled as a special case. This editor component
render fix removes the problem at the root and provides a way to
skip the "flex box clear -> then paint RenderOps" optimization.

**Comment by nazmulidris** [comment]
From https://github.com/r3bl-org/r3bl_rs_utils/commit/ec698cd4c7d7fe4aad37d0c7394b3dfeb2c02f96: 

Fix rendering in all components & remove heuristics for paint optimizations

**Comment by nazmulidris** [comment]
From https://github.com/r3bl-org/r3bl_rs_utils/commit/8aff8932330641c8b008258502d50ffeb2275dd6:

With https://github.com/r3bl-org/r3bl_rs_utils/issues/54 it became
apparent that it is necessary for each RenderOp that paints text to
take care of it's entire display area. The easy solution was to add
empty spaces to fill in that area after painting (to remove any
ghosting from a previous render).

**Comment by nazmulidris** [comment]
Moving the following bugs to backlog, since this fix is so effective at removing flickering!
- https://github.com/r3bl-org/r3bl_rs_utils/issues/46
- https://github.com/r3bl-org/r3bl_rs_utils/issues/24
